homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 32.0512408000
  longitude: 119.8240777600
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Customization file
  customize: !include customize.yaml 
  packages: !include_dir_named packages
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:
  themes:
    night:
      # 主体
      primary-color: '#5294E2'                                                      
      accent-color: '#E45E65'                                                         
      dark-primary-color: 'var(--accent-color)'                                       
      light-primary-color: 'var(--accent-color)'                                      

      # 文字
      primary-text-color: '#FFFFFF'                                                   
      text-primary-color: 'var(--primary-text-color)'                                 
      secondary-text-color: '#5294E2'                                                 
      disabled-text-color: '#7F848E'                                                  
      label-badge-border-color: 'green'                                              

      # 背景
      primary-background-color: '#383C45'                                             
      secondary-background-color: '#383C45'                                           
      divider-color: 'rgba(0, 0, 0, .12)'                                             

      # 表格
      table-row-background-color: '#353840'                                           
      table-row-alternative-background-color: '#3E424B'                               

      # 导航菜单
      paper-listbox-color: 'var(--primary-color)'                                     
      paper-listbox-background-color: '#2E333A'                                       
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#414A59'                                                       

      # 卡片
      paper-card-header-color: 'var(--accent-color)'                                  
      paper-card-background-color: '#434954'                                          
      paper-dialog-background-color: '#434954'                                        
      paper-item-icon-color: 'var(--primary-text-color)'                             
      paper-item-icon-active-color: '#F9C536'                                         
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#434954'                               
      paper-tabs-selection-bar-color: 'green'

      # 标签
      label-badge-red: 'var(--accent-color)'                                         
      label-badge-text-color: 'var(--primary-text-color)'                             
      label-badge-background-color: '#2E333A'                                         

      # 开关
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'

      # 滑块
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'

      # Google
      google-red-500: '#E45E65'
      google-green-500: '#39E949'
 
# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
   api_password: *********
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
#sun:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech

    
# Cloud
cloud:



ios:
