sensor:
  - platform: PhicommTokenGetter
    name: tokengetter
    phicommAccount : 17602516209
    phicommPassowrd: Yxytr123
    tokenPath: '/home/homeassistant/.homeassistant/phicomm_token.txt'

input_boolean:
  phicomm_token_reset:
    name: 重试
    icon: mdi:lock-reset
    initial: false

group:
  tokengetter:
    name: 斐讯Token获取
    view: no
    entities:
      - input_boolean.phicomm_token_reset
      - sensor.tokengetter