switch:
  - platform: PhicommDC1
    name: dc1
    hidden: true
    mac: '2C:3A:E8:47:A2:6B'
    ports: {'1':'dc1_s1','2':'dc1_s2','3':'dc1_s3'}
    tokenPath: '/home/homeassistant/.homeassistant/phicomm_token.txt'
  - platform: template
    switches:
      dc1_template:
        friendly_name: 总开关
        value_template: "{{ is_state('switch.dc1', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1
      dc1_s1_template:
        friendly_name: 位置1
        value_template: "{{ is_state('switch.dc1_s1', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1_s1
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1_s1
      dc1_s2_template:
        friendly_name: 位置2
        value_template: "{{ is_state('switch.dc1_s2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1_s2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1_s2
      dc1_s3_template:
        friendly_name: 位置3
        value_template: "{{ is_state('switch.dc1_s3', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1_s3
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1_s3
sensor:
  - platform: template
    sensors:
      dc1_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1.attributes.v }}"
        unit_of_measurement: V
      dc1_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1.attributes.p }}"
        unit_of_measurement: W
      dc1_totale:
        friendly_name: 累计用电
        value_template: "{{ states.switch.dc1.attributes.totalelect }}"
        unit_of_measurement: 度

group:
  dc1:
    name: DC1插排
    view: no
    control: hidden
    entities:
      - sensor.dc1_v
      - sensor.dc1_p
      - sensor.dc1_totale
      - switch.dc1_template
      - switch.dc1_s1_template
      - switch.dc1_s2_template
      - switch.dc1_s3_template