binary_sensor:
  - platform: mqtt
    name: "renti"
    state_topic: "/esp/renti/13"
    qos: 1
    payload_on: "1"
    payload_off: "0"
    device_class: motion
    
    
group:
 renti:
  name: 人体
  view: no
  entities:
    - binary_sensor.renti